import { issueAccessToken, newRefreshToken, newInviteToken, hashRefreshToken, hashInviteToken, verifyPassword, hashPassword, REFRESH_TTL_SECONDS } from '../auth.js';
import { send, badRequest, unauthenticated, forbidden, notFound, conflict, gone, normalizeTs, selfRoleChange, deviceBusy } from '../http.js';
import { newId, nowIso, bumpPermVersion } from '../db.js';
import { resolve, resolveDevices, assertCan, assertMayGrant, assertCanStartSession } from '../permissions.js';
import { assertRoleExists, assertCanModify, assertNotLastOwner, endActiveSessions, snapshotAuthority, sessionExpiry } from '../lifecycle.js';
import { audit, auditDenials } from '../audit.js';

const cookie = (req, name) => Object.fromEntries(String(req.headers.cookie ?? '').split(';').map((v) => v.trim().split('=')))[name];
const refreshCookie = (raw, maxAge = REFRESH_TTL_SECONDS) => 'rt=' + raw + '; HttpOnly; SameSite=Strict; Secure; Path=/v1/auth/refresh; Max-Age=' + maxAge;
const requiredText = (value, name, max = 200) => { if (typeof value !== 'string' || !value.trim()) throw badRequest(name + ' is required'); const clean=value.trim(); if(clean.length>max)throw badRequest(name+' is too long'); return clean; };
const activeMembership = (db,userId,orgId) => db.prepare("SELECT m.*,o.name AS org_name,o.theme FROM memberships m JOIN organizations o ON o.id=m.org_id AND o.deleted_at IS NULL WHERE m.user_id=? AND m.org_id=? AND m.status='active'").get(userId,orgId);
const orgsFor = (db,userId) => db.prepare("SELECT o.id,o.name,o.theme,m.role FROM memberships m JOIN organizations o ON o.id=m.org_id AND o.deleted_at IS NULL WHERE m.user_id=? AND m.status='active' ORDER BY o.name").all(userId);
const tokenBody = (db,secret,m,userId) => ({token:issueAccessToken({userId,orgId:m.org_id,role:m.role,permVersion:m.perm_version},secret),role:m.role,orgId:m.org_id,orgs:orgsFor(db,userId)});
function issueRefresh(db,userId,familyId=null){const raw=newRefreshToken();db.prepare('INSERT INTO refresh_tokens(id,user_id,token_hash,family_id,expires_at) VALUES(?,?,?,?,?)').run(newId('rft'),userId,hashRefreshToken(raw),familyId??newId('fam'),new Date(Date.now()+REFRESH_TTL_SECONDS*1000).toISOString());return raw;}
const visibleDevice=(db,org,id)=>db.prepare('SELECT * FROM devices WHERE id=? AND org_id=? AND deleted_at IS NULL').get(id,org);
const visibleMember=(db,org,id)=>db.prepare('SELECT m.*,u.email,u.name FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.org_id=? AND m.user_id=?').get(org,id);
const mapDb=(r)=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase()),v]));

export function registerRoutes(router,{db,secret}){
 router.post('/v1/auth/login',(ctx,p,res)=>{const email=requiredText(ctx.body.email,'email').toLowerCase(),password=requiredText(ctx.body.password,'password',500);const user=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!user||!verifyPassword(password,user.password_hash))throw unauthenticated('invalid email or password');const memberships=orgsFor(db,user.id);if(!memberships.length)throw unauthenticated('invalid email or password');const chosen=ctx.body.orgId?memberships.find(m=>m.id===ctx.body.orgId):memberships[0];if(!chosen)throw unauthenticated('invalid organization');const m=activeMembership(db,user.id,chosen.id),raw=issueRefresh(db,user.id);res.setHeader('set-cookie',refreshCookie(raw));send(res,200,{...tokenBody(db,secret,m,user.id),user:{id:user.id,email:user.email,name:user.name}});});
 router.post('/v1/auth/refresh',(ctx,p,res)=>{const raw=cookie(ctx.req,'rt');if(!raw)throw unauthenticated();const row=db.prepare('SELECT * FROM refresh_tokens WHERE token_hash=?').get(hashRefreshToken(raw)),now=nowIso();if(!row)throw unauthenticated();if(row.revoked_at){db.prepare('UPDATE refresh_tokens SET revoked_at=coalesce(revoked_at,?) WHERE family_id=?').run(now,row.family_id);throw unauthenticated('refresh token replayed');}if(row.expires_at<=now)throw unauthenticated('refresh token expired');const m=db.prepare("SELECT * FROM memberships WHERE user_id=? AND status='active' ORDER BY org_id LIMIT 1").get(row.user_id);if(!m)throw unauthenticated();const next=db.transaction(()=>{db.prepare('UPDATE refresh_tokens SET revoked_at=? WHERE id=?').run(now,row.id);return issueRefresh(db,row.user_id,row.family_id);})();res.setHeader('set-cookie',refreshCookie(next));send(res,200,tokenBody(db,secret,m,row.user_id));});
 router.post('/v1/auth/token',(ctx,p,res)=>{const orgId=requiredText(ctx.body.orgId,'orgId'),m=activeMembership(db,ctx.userId,orgId);if(!m)throw notFound();send(res,200,tokenBody(db,secret,m,ctx.userId));});
 router.get('/v1/auth/me',(ctx,p,res)=>{const user=db.prepare('SELECT id,email,name FROM users WHERE id=?').get(ctx.userId);send(res,200,{user,...tokenBody(db,secret,ctx.membership,ctx.userId),permissions:resolve(db,ctx).permissions});});
 router.get('/v1/orgs',(ctx,p,res)=>send(res,200,{orgs:orgsFor(db,ctx.userId)}));
 router.post('/v1/orgs',(ctx,p,res)=>{const name=requiredText(ctx.body.name,'name'),id=newId('org'),themes=['cobalt','amber','emerald','violet'],theme=themes[Math.floor(Math.random()*themes.length)];db.transaction(()=>{db.prepare('INSERT INTO organizations(id,name,theme) VALUES(?,?,?)').run(id,name,theme);db.prepare("INSERT INTO memberships(id,org_id,user_id,role,status,joined_at) VALUES(?,?,?,'owner','active',?)").run(newId('mem'),id,ctx.userId,nowIso());audit(db,{orgId:id,actorId:ctx.userId,action:'org.create',targetType:'organization',targetId:id,result:'allow',requestId:ctx.requestId});})();send(res,201,{id,name,theme,role:'owner'});});
 router.patch('/v1/orgs/:org',(ctx,p,res)=>{assertCan(db,ctx,'org:update');const name=requiredText(ctx.body.name,'name');db.prepare('UPDATE organizations SET name=? WHERE id=? AND deleted_at IS NULL').run(name,p.org);send(res,200,{id:p.org,name});});
 router.delete('/v1/orgs/:org',(ctx,p,res)=>{assertCan(db,ctx,'org:delete');db.prepare('UPDATE organizations SET deleted_at=? WHERE id=? AND deleted_at IS NULL').run(nowIso(),p.org);send(res,204);});
 router.get('/v1/orgs/:org/members',(ctx,p,res)=>{assertCan(db,ctx,'user:read');send(res,200,{members:db.prepare('SELECT u.id,u.email,u.name,m.role,m.status,m.joined_at,m.perm_version FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.org_id=? ORDER BY u.name').all(p.org).map(mapDb)});});
 router.patch('/v1/orgs/:org/members/:userId',(ctx,p,res)=>{assertCan(db,ctx,'user:role:update');if(p.userId===ctx.userId)throw selfRoleChange();assertRoleExists(db,ctx.body.role);const t=visibleMember(db,p.org,p.userId);if(!t)throw notFound();assertCanModify(db,ctx.role,t.role);if(ctx.body.role==='owner'&&ctx.role!=='owner')throw forbidden('only owners may assign owner','role_rank');if(t.role==='owner'&&ctx.body.role!=='owner')assertNotLastOwner(db,p.org,p.userId);db.prepare('UPDATE memberships SET role=?,perm_version=perm_version+1 WHERE org_id=? AND user_id=?').run(ctx.body.role,p.org,p.userId);send(res,200,{userId:p.userId,role:ctx.body.role});});
 router.post('/v1/orgs/:org/members/:userId/suspend',(ctx,p,res)=>{assertCan(db,ctx,'user:remove');const t=visibleMember(db,p.org,p.userId);if(!t)throw notFound();assertCanModify(db,ctx.role,t.role);assertNotLastOwner(db,p.org,p.userId);db.transaction(()=>{db.prepare("UPDATE memberships SET status='suspended',perm_version=perm_version+1 WHERE org_id=? AND user_id=?").run(p.org,p.userId);endActiveSessions(db,{orgId:p.org,userId:p.userId,reason:'user_suspended'});})();send(res,200,{status:'suspended'});});
 router.delete('/v1/orgs/:org/members/:userId/suspend',(ctx,p,res)=>{assertCan(db,ctx,'user:remove');const t=visibleMember(db,p.org,p.userId);if(!t)throw notFound();assertCanModify(db,ctx.role,t.role);db.prepare("UPDATE memberships SET status='active',perm_version=perm_version+1 WHERE org_id=? AND user_id=? AND status='suspended'").run(p.org,p.userId);send(res,200,{status:'active'});});
 router.delete('/v1/orgs/:org/members/me',(ctx,p,res)=>{assertNotLastOwner(db,p.org,ctx.userId);db.transaction(()=>{db.prepare("UPDATE memberships SET status='removed',perm_version=perm_version+1 WHERE org_id=? AND user_id=?").run(p.org,ctx.userId);endActiveSessions(db,{orgId:p.org,userId:ctx.userId,reason:'membership_removed'});})();send(res,204);});
 router.delete('/v1/orgs/:org/members/:userId',(ctx,p,res)=>{assertCan(db,ctx,'user:remove');const t=visibleMember(db,p.org,p.userId);if(!t)throw notFound();assertCanModify(db,ctx.role,t.role);assertNotLastOwner(db,p.org,p.userId);db.transaction(()=>{db.prepare("UPDATE memberships SET status='removed',perm_version=perm_version+1 WHERE org_id=? AND user_id=?").run(p.org,p.userId);endActiveSessions(db,{orgId:p.org,userId:p.userId,reason:'membership_removed'});})();send(res,204);});
 router.get('/v1/orgs/:org/invites',(ctx,p,res)=>{assertCan(db,ctx,'user:invite');send(res,200,{invites:db.prepare('SELECT id,email,role,expires_at,created_at FROM invites WHERE org_id=? AND accepted_at IS NULL AND revoked_at IS NULL ORDER BY created_at DESC').all(p.org).map(mapDb)});});
 router.post('/v1/orgs/:org/invites',(ctx,p,res)=>{assertCan(db,ctx,'user:invite');const email=requiredText(ctx.body.email,'email').toLowerCase(),role=requiredText(ctx.body.role,'role');assertRoleExists(db,role);const ranks=Object.fromEntries(db.prepare('SELECT key,rank FROM roles').all().map(r=>[r.key,r.rank]));if(role==='owner'&&ctx.role!=='owner')throw forbidden('only owners may invite owners','role_rank');if(ranks[ctx.role]<ranks[role])throw forbidden('cannot assign this role','role_rank');if(db.prepare("SELECT 1 FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.org_id=? AND u.email=? AND m.status='active'").get(p.org,email))throw conflict('already a member');const raw=newInviteToken(),id=newId('inv'),exp=new Date(Date.now()+7*86400000).toISOString();try{db.prepare('INSERT INTO invites(id,org_id,email,role,token_hash,invited_by,expires_at) VALUES(?,?,?,?,?,?,?)').run(id,p.org,email,role,hashInviteToken(raw),ctx.userId,exp);}catch(e){if(e.code?.startsWith('SQLITE_CONSTRAINT'))throw conflict('live invite already exists');throw e;}send(res,201,{id,email,role,expiresAt:exp,inviteToken:raw});});
 router.delete('/v1/orgs/:org/invites/:id',(ctx,p,res)=>{assertCan(db,ctx,'user:invite');const n=db.prepare('UPDATE invites SET revoked_at=? WHERE id=? AND org_id=? AND accepted_at IS NULL AND revoked_at IS NULL').run(nowIso(),p.id,p.org).changes;if(!n)throw notFound();send(res,204);});
 const inviteByToken=(raw)=>db.prepare('SELECT i.*,o.name org_name FROM invites i JOIN organizations o ON o.id=i.org_id WHERE i.token_hash=?').get(hashInviteToken(raw));
 router.get('/v1/invites/:token',(ctx,p,res)=>{const i=inviteByToken(p.token);if(!i)throw notFound();if(i.revoked_at||i.expires_at<=nowIso())throw gone();if(i.accepted_at)throw conflict('invite already accepted');send(res,200,{orgName:i.org_name,role:i.role,email:i.email,expiresAt:i.expires_at});});
 router.post('/v1/invites/:token/accept',(ctx,p,res)=>{const i=inviteByToken(p.token);if(!i)throw notFound();if(i.revoked_at||i.expires_at<=nowIso())throw gone();if(i.accepted_at)throw conflict('invite already accepted');const name=requiredText(ctx.body.name,'name'),password=requiredText(ctx.body.password,'password',500);let user=db.prepare('SELECT * FROM users WHERE email=?').get(i.email);const m=db.transaction(()=>{if(!user){const id=newId('usr');db.prepare('INSERT INTO users(id,email,name,password_hash) VALUES(?,?,?,?)').run(id,i.email,name,hashPassword(password));user=db.prepare('SELECT * FROM users WHERE id=?').get(id);}const prior=db.prepare('SELECT * FROM memberships WHERE org_id=? AND user_id=?').get(i.org_id,user.id);if(prior&&prior.status==='active')throw conflict('already a member');if(prior)db.prepare("UPDATE memberships SET role=?,status='active',joined_at=?,perm_version=perm_version+1 WHERE id=?").run(i.role,nowIso(),prior.id);else db.prepare("INSERT INTO memberships(id,org_id,user_id,role,status,invited_by,joined_at) VALUES(?,?,?,?, 'active',?,?)").run(newId('mem'),i.org_id,user.id,i.role,i.invited_by,nowIso());db.prepare('UPDATE invites SET accepted_at=?,accepted_by=? WHERE id=? AND accepted_at IS NULL').run(nowIso(),user.id,i.id);return activeMembership(db,user.id,i.org_id);})();const raw=issueRefresh(db,user.id);res.setHeader('set-cookie',refreshCookie(raw));send(res,200,{...tokenBody(db,secret,m,user.id),user:{id:user.id,email:user.email,name:user.name}});});
 router.get('/v1/orgs/:org/devices',(ctx,p,res)=>{assertCan(db,ctx,'device:list');const rows=db.prepare('SELECT id,name,kind,online,created_at FROM devices WHERE org_id=? AND deleted_at IS NULL ORDER BY name').all(p.org);const r=resolveDevices(db,{userId:ctx.userId,orgId:p.org,deviceIds:rows.map(x=>x.id)});send(res,200,{devices:rows.filter(x=>r.byDevice[x.id]['device:view'].effect==='allow').map(x=>({...mapDb(x),online:!!x.online,permissions:r.byDevice[x.id]}))});});
 router.get('/v1/orgs/:org/devices/:id',(ctx,p,res)=>{const d=visibleDevice(db,p.org,p.id);if(!d)throw notFound();assertCan(db,ctx,'device:view',p.id);send(res,200,{...mapDb(d),online:!!d.online,permissions:resolve(db,{userId:ctx.userId,orgId:p.org,deviceId:p.id}).permissions});});
 router.post('/v1/orgs/:org/devices',(ctx,p,res)=>{assertCan(db,ctx,'device:provision');const id=newId('dev'),name=requiredText(ctx.body.name,'name'),kind=requiredText(ctx.body.kind,'kind');try{db.prepare('INSERT INTO devices(id,org_id,name,kind,online) VALUES(?,?,?,?,?)').run(id,p.org,name,kind,ctx.body.online?1:0);}catch(e){if(e.code?.startsWith('SQLITE_CONSTRAINT'))throw badRequest('invalid device');throw e;}send(res,201,{id,name,kind,online:!!ctx.body.online});});
 router.patch('/v1/orgs/:org/devices/:id',(ctx,p,res)=>{if(!visibleDevice(db,p.org,p.id))throw notFound();assertCan(db,ctx,'device:update',p.id);const name=requiredText(ctx.body.name,'name');db.prepare('UPDATE devices SET name=? WHERE id=?').run(name,p.id);send(res,200,{id:p.id,name});});
 router.delete('/v1/orgs/:org/devices/:id',(ctx,p,res)=>{if(!visibleDevice(db,p.org,p.id))throw notFound();assertCan(db,ctx,'device:provision',p.id);db.transaction(()=>{endActiveSessions(db,{orgId:p.org,deviceId:p.id,reason:'device_transferred'});db.prepare('UPDATE devices SET deleted_at=? WHERE id=?').run(nowIso(),p.id);})();send(res,204);});
 router.post('/v1/orgs/:org/devices/:id/transfer',(ctx,p,res)=>{if(!visibleDevice(db,p.org,p.id))throw notFound();assertCan(db,ctx,'device:provision',p.id);const target=requiredText(ctx.body.orgId,'orgId');if(!activeMembership(db,ctx.userId,target))throw notFound();assertCan(db,{...ctx,orgId:target},'device:provision');db.transaction(()=>{endActiveSessions(db,{orgId:p.org,deviceId:p.id,reason:'device_transferred'});db.prepare('UPDATE devices SET org_id=? WHERE id=?').run(target,p.id);})();send(res,200,{id:p.id,orgId:target});});
 router.get('/v1/orgs/:org/grants',(ctx,p,res)=>{assertCan(db,ctx,'user:read');const rows=db.prepare('SELECT g.*,group_concat(gp.permission) permissions FROM grants g JOIN grant_permissions gp ON gp.grant_id=g.id WHERE g.org_id=? AND g.revoked_at IS NULL GROUP BY g.id ORDER BY g.created_at DESC').all(p.org).map(r=>({...mapDb(r),permissions:r.permissions.split(',')}));send(res,200,{grants:rows});});
 router.post('/v1/orgs/:org/grants',(ctx,p,res)=>{assertCan(db,ctx,'grant:create');const {userId,deviceId=null,effect,permissions,startsAt=null}=ctx.body;if(userId===ctx.userId)throw forbidden('self grants are forbidden','self_grant');if(effect!=='allow'&&effect!=='deny')throw badRequest('effect must be allow or deny');const member=visibleMember(db,p.org,userId);if(!member||member.status!=='active')throw notFound();if(deviceId&&!visibleDevice(db,p.org,deviceId))throw notFound();const expiresAt=normalizeTs(ctx.body.expiresAt,'expiresAt');if(expiresAt&&expiresAt<=nowIso()){const e=badRequest('grant expiry must be in the future','expired_grant');e.code='GRANT_EXPIRED';throw e;}assertMayGrant(db,ctx,permissions,deviceId);const id=newId('grt');try{db.transaction(()=>{db.prepare('INSERT INTO grants(id,org_id,user_id,device_id,effect,starts_at,expires_at,created_by) VALUES(?,?,?,?,?,?,?,?)').run(id,p.org,userId,deviceId,effect,normalizeTs(startsAt,'startsAt'),expiresAt,ctx.userId);const s=db.prepare('INSERT INTO grant_permissions(grant_id,permission) VALUES(?,?)');for(const permission of new Set(permissions))s.run(id,permission);bumpPermVersion(db,{orgId:p.org,userId});audit(db,{orgId:p.org,actorId:ctx.userId,action:'grant.create',targetType:'grant',targetId:id,result:'allow',requestId:ctx.requestId});})();}catch(e){if(e.code==='SQLITE_CONSTRAINT_FOREIGNKEY')throw badRequest('unknown permission','unknown_permission');throw e;}send(res,201,{id,userId,deviceId,effect,permissions});});
 router.delete('/v1/orgs/:org/grants/:id',(ctx,p,res)=>{assertCan(db,ctx,'grant:revoke');const g=db.prepare('SELECT * FROM grants WHERE id=? AND org_id=? AND revoked_at IS NULL').get(p.id,p.org);if(!g)throw notFound();db.transaction(()=>{db.prepare('UPDATE grants SET revoked_at=? WHERE id=?').run(nowIso(),p.id);bumpPermVersion(db,{orgId:p.org,userId:g.user_id});})();send(res,204);});
 router.post('/v1/orgs/:org/sessions',(ctx,p,res)=>auditDenials(db,ctx,{action:'session.start',targetType:'device',targetId:ctx.body.deviceId},()=>{const d=visibleDevice(db,p.org,ctx.body.deviceId);if(!d)throw notFound();assertCanStartSession(db,ctx,ctx.body.mode,d.id);const id=newId('ses'),expiresAt=sessionExpiry(db,p.org),authority=snapshotAuthority(db,{userId:ctx.userId,orgId:p.org,deviceId:d.id});try{db.transaction(()=>{db.prepare("INSERT INTO sessions(id,org_id,user_id,device_id,mode,state,authorized_by,expires_at) VALUES(?,?,?,?,?,'active',?,?)").run(id,p.org,ctx.userId,d.id,ctx.body.mode,JSON.stringify(authority),expiresAt);audit(db,{orgId:p.org,actorId:ctx.userId,action:'session.start',targetType:'device',targetId:d.id,result:'allow',requestId:ctx.requestId});})();}catch(e){if(e.code?.startsWith('SQLITE_CONSTRAINT_UNIQUE'))throw deviceBusy();throw e;}send(res,201,{id,orgId:p.org,userId:ctx.userId,deviceId:d.id,mode:ctx.body.mode,state:'active',expiresAt,authorizedBy:authority});}));
 router.get('/v1/orgs/:org/sessions',(ctx,p,res)=>{assertCan(db,ctx,'session:view');send(res,200,{sessions:db.prepare('SELECT * FROM sessions WHERE org_id=? ORDER BY started_at DESC').all(p.org)});});
 router.get('/v1/sessions/:id',(ctx,p,res)=>{const s=db.prepare('SELECT * FROM sessions WHERE id=? AND org_id=?').get(p.id,ctx.orgId);if(!s)throw notFound();if(s.user_id!==ctx.userId)assertCan(db,ctx,'session:view',s.device_id);send(res,200,s);});
 router.delete('/v1/sessions/:id',(ctx,p,res)=>{const s=db.prepare('SELECT * FROM sessions WHERE id=? AND org_id=?').get(p.id,ctx.orgId);if(!s)throw notFound();if(s.user_id!==ctx.userId)assertCan(db,ctx,'session:terminate',s.device_id);db.prepare("UPDATE sessions SET state='ended',end_reason=?,ended_at=? WHERE id=? AND state<>'ended'").run(s.user_id===ctx.userId?'user_stopped':'admin_terminated',nowIso(),p.id);send(res,204);});
 router.get('/v1/orgs/:org/users/:userId/effective',(ctx,p,res)=>{if(p.userId!==ctx.userId)assertCan(db,ctx,'user:read');if(!visibleMember(db,p.org,p.userId))throw notFound();send(res,200,resolve(db,{userId:p.userId,orgId:p.org,deviceId:ctx.query.get('deviceId')}));});
 router.get('/v1/orgs/:org/audit',(ctx,p,res)=>{assertCan(db,ctx,'audit:read');const limit=ctx.query.has('limit')?Number(ctx.query.get('limit')):50,offset=ctx.query.has('offset')?Number(ctx.query.get('offset')):0;if(!Number.isInteger(limit)||limit<1||limit>200||!Number.isInteger(offset)||offset<0)throw badRequest('invalid pagination');send(res,200,{events:db.prepare('SELECT * FROM audit_events WHERE org_id=? ORDER BY at DESC,id DESC LIMIT ? OFFSET ?').all(p.org,limit,offset)});});
}
